### ISSUE TITLE
No Shiny application exists at the path "/app"

### ISSUE THREAD

**Issue by stan1233** [chasemc/mzEasy#1]
Hi, 
    When i install this by the way that you gave, there was a problem.
---------------------------
Startup failed with error(s):

No Shiny application exists at the path "/app"
---------------------------

I already add the path(C:\Program Files\ProteoWizard\ProteoWizard 3.0.18182.5406cdbf0) to  Specify_ProteoWizard_Location.txt. 

maby need add the path into the system environment variable?
Hoping my problem can be solved.,thanks!

Stan

**Comment by chasemc** [comment]
You will need internet the first time you run the app. Let me know if that solves the issue. If not, send the log (within the folder mzeasy installed to) to chasec288 at Gmail dot com

**Comment by chasemc** [comment]
Great! Thanks for the email of the logs.


Quick question: Do you happen to be accessing mzEasy from China?  Is google.com still blocked?

I ask because mzEasy uses  https://github.com/ficonsulting/RInno, which checks for internet by first pinging "google.com"

**Comment by stan1233** [comment]
Hi, Chasae

     I am a Chinese graduate student who are interested in molecular
networks.
google.com is still blocked, but we have some special way to access it. lol

But, most of us are use a proxy only for website, so maybe that is the
reason why can not running mzEasy.

If ping another ip like "amazon.com or ebay.com" more likely will running.

Thanks for your reply!

Sincerely,
Stan

Chase Clark <notifications@github.com> 于2018年7月6日周五 上午12:03写道：

**Comment by chasemc** [comment]
Try looking in the mzEasy installation folder for two files:
`get_app_from_app_url.R`
and
`package_manager.R`

replace `google.com` with the url of any website you are able to access without proxy

**Comment by chasemc** [comment]
Feel free to re-open this issue if the problem persists

**Comment by stan1233** [comment]
Thank you for your help, my problem has been solved, sorry, I can't reply to you in the first time.

**Comment by chasemc** [comment]
No need to apologize, I closed it so you wouldn't have to respond if you were busy. If there are any other problems feel free to open issues. Thanks for the feedback 👍
